### ISSUE TITLE
not working (Fixed)

### ISSUE THREAD

**Issue by Devolando** [Qmirdev/Simple-Python-Chatbot#1]
chat bot is not working

**Comment by q31r** [comment]
> chat bot is not working

Dear Devolando,

Thank you for bringing this to my attention. You are absolutely right, it seems that some lines in my chatbot file have gone missing. It appears that they were accidentally deleted, and I apologize for any inconvenience caused. I will make sure to rectify this issue promptly and restore the missing lines.

Thank you for your understanding.

Best regards,

**Comment by Devolando** [comment]
> > chat bot is not working
> 
> Dear Devolando,
> 
> Thank you for bringing this to my attention. You are absolutely right, it seems that some lines in my chatbot file have gone missing. It appears that they were accidentally deleted, and I apologize for any inconvenience caused. I will make sure to rectify this issue promptly and restore the missing lines.
> 
> Thank you for your understanding.
> 
> Best regards,

Thanks, it works well !
