### ISSUE TITLE
No logs for chatbot

### ISSUE THREAD

**Issue by Devolando** [Qmirdev/Simple-Python-Chatbot#2]
Loved the basic concept of the bot, In order to **train the bot** effectively, it is necessary to store the logs and messages exchanged between the chat bot and the user. However, it seems that there is currently no data available. Is there a way to address this issue and ensure that the necessary information is being captured for training purposes?

**Comment by q31r** [comment]
> Loved the basic concept of the bot, In order to **train the bot** effectively, it is necessary to store the logs and messages exchanged between the chat bot and the user. However, it seems that there is currently no data available. Is there a way to address this issue and ensure that the necessary information is being captured for training purposes?

Dear Devolando,

Thank you for your valuable feedback. I completely agree with you. In the upcoming update, I will ensure that the chatbot logs all interactions between the user and itself. This will help us gather comprehensive data for analysis and improvement.

Best regards,
